### PR TITLE
check existence of a listener function before removing

### PR DESCRIPTION
**Pull request by amaha877**
Part of the fix for the exception raised in 
https://jira.dolby.net/jira/browse/DIOS-7384

### CODE REVIEW

**Comment by murillo128** [comment]
not sure if I like to silently ignore caller errors, if the app tries to remove a non existing even listener, we should raise an exception and the caller code should be fixed

**Comment by mildsunrise** [comment]
i was thinking the same... we could do a middle ground and log an error, maybe?

**Comment by mildsunrise** [comment]
my rationale is: calling .off() with a nonexistent listener is almost certainly a programming mistake we have to debug.
but given that .off() is often called at cleanup, and interrupting cleanup can be have serious implications, we might want to let it continue and just log the error

**Comment by amaha877** [comment]
Totally agreed that its certainly a code flow bug. I sort of went with it  as a bandaid because the `wrap()` method also similar checks.
```
#wrap(listener)
	{
		let wrapped = this.#map.get(listener);
		if (!wrapped)
		{
			wrapped = (/** @type {any[]} */ ...args)=>{
				try {
					listener(...args);
				} catch(e) {
					setImmediate(()=>{throw e});
				}
			};
			this.#map.set(listener,wrapped);
		}
		return wrapped;
	}
```
 However, we have to ensure cleanup goes through so I added a try catch finally block in the other PR -> https://github.com/CoSMoSoftware/webrtc-cdn-viewer/pull/166

**Comment by amaha877** [comment]
Canceled

**Pull request closed without merging**
